DROP TABLE IF EXISTS EVE_MARKETORDER_RC;
CREATE TABLE EVE_MARKETORDER_RC(
    UID VARCHAR(32),
    TYPE_ID VARCHAR(32),
    SELL_ORDER_ID VARCHAR(32),
    SELL_PRICE NUMERIC(24,6),
    SELL_TOTAL INTEGER,
    BUY_ORDER_ID VARCHAR(32),
    BUY_PRICE NUMERIC(24,6),
    BUY_TOTAL INTEGER,
    SELL_ORDER_SUM INTEGER,
    SELL_ORDER_TOTAL INTEGER,
    OP_TIME TIMESTAMP,
	REMARK VARCHAR(1024)
);


DROP TABLE IF EXISTS EVE_MONIMARKET_INFO;
CREATE TABLE EVE_MONIMARKET_INFO(
    UID VARCHAR(32),
    TYPE_ID VARCHAR(32),
    TYPE_NAME VARCHAR(90),
    USE_FLAG VARCHAR(1),
    REMARK VARCHAR(255)
);
